### PR TITLE
Fixed string zero termination

### PR DESCRIPTION
**Pull request by DeltaCore**
I needed this lib, nice rewrite.
I fixed a bug where the service string got corrupted. The TXT-record does not work by now.
I will have a look into that as well.

Maybe if that's ok for you i would like to maintain this repo - you can give me then write access to this repo, this would make changes alot easier for me, but only if you are ok with that :)

The platformio lib manifest is connected to your repo and i would like to use that in some projects.

Marcel - deltacore

### CODE REVIEW

**Comment by TrippyLighting** [comment]
Hi Marcel,

I am glad the library is useful for someone. I'd be happy to add write permission for you.
How do I do that ?

**Comment by DeltaCore** [comment]
You go into the Repo settings: https://github.com/TrippyLighting/EthernetBonjour/settings
Then unter Collaborators -> search for my name: deltacore (The one with the yellow thing on the profile picture :D ) and press "Add collaborator".

That's probably it :)

Thanks in advance :)

**Comment by DeltaCore** [comment]
Hey @TrippyLighting have you tried to give me access? I would like to check on some of the issues and may edit some files.

- Marcel

**Comment by TrippyLighting** [comment]
HI Marcel,

I though I did but apparently I did not :/ Sorry about that!
Ive added you as a collaborator now and you should have received an email from Github with the invitation.

**Pull request merged**
